spring:
  profiles:
    active: dev

---
server:
  port: 8201
spring:
  application:
    name: springcloud-config-client
  profiles:
    active: dev
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: springcloud-config-client
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/